name: Rebase uat onto prod

on:
  push:
    branches:
      - prod

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'uat'
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "ayushsaha111@gmail.com"
          git config --local user.name "github-actions[bot]"

      - name: Rebase onto uat
        run: |
          git fetch origin prod
          git rebase origin/prod

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: 'uat'
          force_with_lease: true