name: Release

on:
  push:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'prod'
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.PAT_TOKEN }}                   

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Semantic Release Packages
        run: yarn global add @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/release-notes-generator semantic-release

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: semantic-release